#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env"
FORCE=0

if [[ "${1:-}" == "--force" ]]; then
  FORCE=1
fi

generate_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 48 | tr -dc 'A-Za-z0-9' | head -c 32
  else
    tr -dc 'A-Za-z0-9' </dev/urandom | head -c 32
  fi
}

if [[ -f "$ENV_FILE" && $FORCE -ne 1 ]]; then
  echo ".env already exists at $ENV_FILE"
  echo "Use --force to regenerate."
  exit 0
fi

DB_USER="applymanager"
DB_NAME="applymanager"
DB_PASSWORD="$(generate_secret)"

cat >"$ENV_FILE" <<EOF
# Generated by scripts/setup-server-env.sh
# $(date -u +"%Y-%m-%dT%H:%M:%SZ")

DB_USER=$DB_USER
DB_PASSWORD=$DB_PASSWORD
DB_NAME=$DB_NAME
EOF

chmod 600 "$ENV_FILE" || true

echo
echo "Created secure server env file:"
echo "  $ENV_FILE"
echo
echo "Next steps:"
echo "  1) Review .env"
echo "  2) Start stack: ./scripts/run-all.sh up"
echo
